name: petclinic-pipeline CI/CD

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          ref: main

      - name: Checking out Spring PetClinic from GitHub...
        run: echo "Checking out Spring PetClinic from GitHub..."

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Building Spring PetClinic...
        run: echo "Building Spring PetClinic..."

      - name: Build with Maven
        run: ./mvnw clean compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Running tests...
        run: echo "Running tests..."

      - name: Run tests
        run: ./mvnw test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-petclinic
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Packaging application...
        run: echo "Packaging application..."

      - name: Package with Maven
        run: ./mvnw package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar
